spring:
  application:
    name: Jogos API
  datasource:
    url: jdbc:h2:mem:jogos
    username: sa
    password: "1234"
  jpa:
    database-plataform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enable: true
      path: /h2-console